apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  serviceName: "nginx-headless"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-nginx-content
        image: nynregistry.azurecr.io/nginx-web:latest
        command: ['sh', '-c', 'cp -r /usr/share/nginx/html/* /mnt && chmod -R 755 /mnt']
        volumeMounts:
        - name: www
          mountPath: /mnt
 
      containers:
      - name: nginx
        image: nynregistry.azurecr.io/nginx-web:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi